# Simplified Docker Compose for botgarden-core

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: bg-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    command: >
      sh -c "
        envsubst '$$DOMAIN' < /etc/nginx/templates/botgarden-ssl.conf.template > /etc/nginx/conf.d/default.conf &&
        nginx -g 'daemon off;'
      "
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx:/etc/nginx/templates:ro
      - ./static:/var/www/html:ro
      - ./certs:/etc/nginx/certs:ro
      - ./logs/nginx:/var/log/nginx
    environment:
      - TZ=${TZ:-UTC}
      - DOMAIN=${DOMAIN}
    networks:
      - botgarden
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: bg-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ:-UTC}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backups:/backups
    networks:
      - botgarden
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres-data:
    driver: local

networks:
  botgarden:
    name: botgarden
    driver: bridge
