version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${BOT_NAME}
    restart: unless-stopped
    environment:
      - BOT_NAME=${BOT_NAME}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_PORT=${BOT_PORT:-8080}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - POSTGRES_HOST=bg-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - TZ=${TZ:-UTC}
    expose:
      - "${BOT_PORT:-8080}"
    networks:
      - botgarden
    volumes:
      - bot-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BOT_PORT:-8080}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  bot-data:
    driver: local

networks:
  botgarden:
    external: true
